#!/bin/bash
#SBATCH --job-name=bbduk_trimming
#SBATCH -n 1
#SBATCH -N 1
#SBATCH -c 8
#SBATCH --mem=30G
#SBATCH --partition=general
#SBATCH --qos=general
#SBATCH --mail-user=alex.frutos@uconn.edu
#SBATCH --mail-type=ALL
#SBATCH -o %x_%j.out
#SBATCH -e %x_%j.err

raw_reads=../data/raw
out_dir=../data/trimmed
mkdir -p $out_dir

module load bbmap

for r1 in $raw_reads/*_1.fastq.gz
do
  r2=${r1/_1.fastq.gz/_2.fastq.gz}
  base=$(basename "$r1" _1.fastq.gz)

  bbduk.sh \
    in1="$r1" \
    in2="$r2" \
    out1="$out_dir/${base}_1_trimmed.fastq.gz" \
    out2="$out_dir/${base}_2_trimmed.fastq.gz" \
    ref=adapters \
    ktrim=r k=31 mink=11 hdist=1 tpe tbo
done
